spider:
  target_url: https://www.1nzb.com
  agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

mongodb:
  url: mongodb://127.0.0.1:27017/
  database: spider
  collection: spider_db


mysql:
  host: 127.0.0.1
  password: root
  port: 3306
  user: root
  database: spider
